- name: Deploy Python Flask App
  hosts: local
  tasks:
    - name: Build image
      shell: docker build -t flask-app:latest .
      args:
        chdir: ../app

    - name: Load image into kind
      shell: kind load docker-image flask-app:latest

    - name: Apply k8s manifest
      shell: kubectl apply -f k8s.yaml
      args:
        chdir: ../app
