- name: Create kind cluster
  hosts: local
  tasks:
    - name: Create kind config
      copy:
        dest: /tmp/kind-config.yaml
        content: |
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
              extraPortMappings:
                - containerPort: 30007
                  hostPort: 30007

    - name: Create kind cluster
      shell: kind create cluster --config=/tmp/kind-config.yaml
